'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';

type Character={id:string;name:string;age:number;role:string;personality:string[];needs:any;goals:string[];location:string;mood:string;current_activity:string;inventory:any;action_count:number;position_x:number;position_y:number};
type World={tick:number;day:number;hour:number;season:string;weather:string;resources:any};
type Event={id:string;tick:number;actor_name:string;action:string;narrative:string;created_at:string};
const initials=(n:string)=>n.slice(0,2).toUpperCase();
const colors=['#d7b98e','#9db7a5','#b8a3cf','#8fb5c7','#c8a9a0','#d0c38c','#a8b8d0','#c29a78','#9dbda9'];
export default function Home(){
 const [world,setWorld]=useState<World|null>(null),[chars,setChars]=useState<Character[]>([]),[events,setEvents]=useState<Event[]>([]),[selected,setSelected]=useState<Character|null>(null),[loading,setLoading]=useState(true);
 const load=async()=>{const [w,c,e]=await Promise.all([supabase.from('world_state').select('*').eq('id',1).single(),supabase.from('characters').select('*').order('name'),supabase.from('world_events').select('*').order('tick',{ascending:false}).order('created_at',{ascending:false}).limit(20)]); if(w.data)setWorld(w.data); if(c.data)setChars(c.data); if(e.data)setEvents(e.data); setLoading(false)};
 useEffect(()=>{load(); const ch=supabase.channel('the-nine-live').on('postgres_changes',{event:'*',schema:'public',table:'characters'},load).on('postgres_changes',{event:'*',schema:'public',table:'world_events'},load).on('postgres_changes',{event:'*',schema:'public',table:'world_state'},load).subscribe(); return()=>{supabase.removeChannel(ch)}},[]);
 const selectedEvents=useMemo(()=>selected?events.filter(e=>e.actor_name===selected.name).slice(0,5):[],[selected,events]);
 if(loading)return <main className="loading">THE NINE <span>initializing world...</span></main>;
 return <main>
  <header className="top"><div><div className="eyebrow">PERSISTENT ARTIFICIAL SOCIETY · EXPERIMENT 001</div><h1>THE <i>NINE</i></h1><p>Nine artificial people. One persistent world. Watch what happens when they remember, decide, interact and change the place they share.</p></div><div className="world-status"><span className="dot"/> WORLD ONLINE <b>DAY {world?.day} · {String(world?.hour).padStart(2,'0')}:00</b></div></header>
  <section className="stats"><div><small>RESIDENTS</small><strong>09</strong></div><div><small>WORLD TICK</small><strong>{world?.tick??0}</strong></div><div><small>SEASON</small><strong>{world?.season?.toUpperCase()}</strong></div><div><small>WEATHER</small><strong>{world?.weather?.toUpperCase()}</strong></div><div className="resources"><small>SHARED RESOURCES</small><span>FOOD {world?.resources?.food??0}</span><span>WOOD {world?.resources?.wood??0}</span><span>STONE {world?.resources?.stone??0}</span><span>TOOLS {world?.resources?.tools??0}</span></div></section>
  <section className="layout"><div className="world"><div className="section-head"><div><small>THE SETTLEMENT</small><h2>Life is happening here.</h2></div><span>click a resident</span></div><div className="map"><div className="sun"/><div className="path p1"/><div className="path p2"/><div className="path p3"/>{chars.map((c,i)=><button key={c.id} className="resident" style={{left:`${50+(Number(c.position_x)||0)*.7}%`,top:`${50-(Number(c.position_y)||0)*.65}%`}} onClick={()=>setSelected(c)}><span className="avatar" style={{background:colors[i%colors.length]}}>{initials(c.name)}</span><span className="label"><b>{c.name}</b><em>{c.current_activity}</em></span></button>)}</div></div>
  <aside><div className="section-head"><div><small>WORLD HISTORY</small><h2>Recent events</h2></div></div><div className="feed">{events.length?events.map(e=><article key={e.id}><div className="event-meta">TICK {e.tick} · {e.action.toUpperCase()}</div><b>{e.actor_name}</b><p>{e.narrative}</p></article>):<p className="empty">The world has not recorded its first event yet.</p>}</div></aside></section>
  <section className="residents"><div className="section-head"><div><small>THE RESIDENTS</small><h2>Nine lives, one shared history.</h2></div></div><div className="cards">{chars.map((c,i)=><button className="card" key={c.id} onClick={()=>setSelected(c)}><span className="avatar" style={{background:colors[i%colors.length]}}>{initials(c.name)}</span><div><h3>{c.name}</h3><small>{c.age} · {c.role}</small><p>{c.mood} · {c.current_activity}</p></div><span className="chev">↗</span></button>)}</div></section>
  {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="avatar big" style={{background:colors[chars.findIndex(x=>x.id===selected.id)%colors.length]}}>{initials(selected.name)}</span><small>{selected.role.toUpperCase()} · AGE {selected.age}</small><h2>{selected.name}</h2><p className="mood">{selected.mood} · {selected.current_activity}</p><div className="bars"><div><span>FOOD</span><b>{selected.needs?.food??0}</b></div><div><span>ENERGY</span><b>{selected.needs?.energy??0}</b></div><div><span>SOCIAL</span><b>{selected.needs?.social??0}</b></div><div><span>HEALTH</span><b>{selected.needs?.health??0}</b></div></div><h4>GOALS</h4><ul>{(selected.goals||[]).map((g:string)=><li key={g}>{g}</li>)}</ul><h4>RECENT MEMORY / HISTORY</h4>{selectedEvents.map(e=><p className="mini" key={e.id}>{e.narrative}</p>)}</div></div>}
  <footer><span>THE NINE · SIMULATION EXPERIMENT 001</span><span>AI behavior is simulated. The system does not claim consciousness.</span></footer>
 </main>
}
