'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import Settlement from './Settlement';
import Avatar from './Avatar';

type Trait={trait:string;weight:number};
type Character={id:string;name:string;age:number;role:string;personality:Trait[]|string[];needs:any;goals:string[];location:string;mood:string;current_activity:string;inventory:any;action_count:number;position_x:number;position_y:number;last_action?:any;last_reason?:string|null};
type World={tick:number;day:number;hour:number;season:string;weather:string;resources:any};
type Event={id:string;tick:number;actor_name:string;action:string;narrative:string;created_at:string;metadata?:any};
type Rel={id:string;character_a:string;character_b:string;affinity:number;trust:number;relationship_label:string};
type Chronicle={day:number;season:string;summary:string;highlights:{tick:number;kind:string;text:string}[];stats:any;first_tick:number;last_tick:number};
const initials=(n:string)=>n.slice(0,2).toUpperCase();
const colors=['#d7b98e','#9db7a5','#b8a3cf','#8fb5c7','#c8a9a0','#d0c38c','#a8b8d0','#c29a78','#9dbda9'];
const traitList=(p:Character['personality']):Trait[]=>(Array.isArray(p)?p:[]).map((x:any)=>typeof x==='string'?{trait:x,weight:.7}:{trait:String(x?.trait??''),weight:Number(x?.weight??0)}).filter(x=>x.trait).sort((a,b)=>b.weight-a.weight);
export default function Home(){
 const [world,setWorld]=useState<World|null>(null),[chars,setChars]=useState<Character[]>([]),[events,setEvents]=useState<Event[]>([]),[rels,setRels]=useState<Rel[]>([]),[chron,setChron]=useState<Chronicle[]>([]),[chronDay,setChronDay]=useState<number|null>(null),[selected,setSelected]=useState<Character|null>(null),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{const [w,c,e,r,ch]=await Promise.all([supabase.from('world_state').select('*').eq('id',1).single(),supabase.from('characters').select('*').order('name'),supabase.from('world_events').select('*').order('tick',{ascending:false}).order('created_at',{ascending:false}).limit(30),supabase.from('relationships').select('id,character_a,character_b,affinity,trust,relationship_label'),supabase.from('day_chronicle').select('*').order('day',{ascending:false}).limit(7)]); if(w.data)setWorld(w.data); if(c.data)setChars(c.data); if(e.data)setEvents(e.data); if(r.data)setRels(r.data); if(ch.data)setChron(ch.data); setLoading(false)},[]);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{const soon=()=>{if(timer.current)clearTimeout(timer.current); timer.current=setTimeout(load,500)}; load(); const ch=supabase.channel('the-nine-live').on('postgres_changes',{event:'*',schema:'public',table:'characters'},soon).on('postgres_changes',{event:'*',schema:'public',table:'world_events'},soon).on('postgres_changes',{event:'*',schema:'public',table:'world_state'},soon).on('postgres_changes',{event:'*',schema:'public',table:'day_chronicle'},soon).subscribe(); return()=>{if(timer.current)clearTimeout(timer.current); supabase.removeChannel(ch)}},[load]);
 // Keep the open drawer in sync with live data.
 useEffect(()=>{setSelected(s=>s?chars.find(c=>c.id===s.id)??s:s)},[chars]);
 const selectedEvents=useMemo(()=>selected?events.filter(e=>e.actor_name===selected.name).slice(0,5):[],[selected,events]);
 const nameOf=useCallback((id:string)=>chars.find(c=>c.id===id)?.name??'?',[chars]);
 const selectedRels=useMemo(()=>selected?rels.filter(r=>r.character_a===selected.id||r.character_b===selected.id).map(r=>({other:nameOf(r.character_a===selected.id?r.character_b:r.character_a),affinity:Number(r.affinity),label:r.relationship_label})).sort((a,b)=>b.affinity-a.affinity):[],[selected,rels,nameOf]);
 const activeChron=chron.find(c=>c.day===chronDay)??chron[0];
 if(loading)return <main className="loading">THE NINE <span>initializing world...</span></main>;
 return <main>
  <header className="top"><div><div className="eyebrow">PERSISTENT ARTIFICIAL SOCIETY · EXPERIMENT 001</div><h1>THE <i>NINE</i></h1><p>Nine artificial people. One persistent world. Watch what happens when they remember, decide, interact and change the place they share.</p></div><div className="world-status"><span className="dot"/> WORLD ONLINE <b>DAY {world?.day} · {String(world?.hour).padStart(2,'0')}:00</b></div></header>
  <section className="stats"><div><small>RESIDENTS</small><strong>09</strong></div><div><small>WORLD TICK</small><strong>{world?.tick??0}</strong></div><div><small>SEASON</small><strong>{world?.season?.toUpperCase()}</strong></div><div><small>WEATHER</small><strong>{world?.weather?.toUpperCase()}</strong></div><div className="resources"><small>SHARED RESOURCES</small><span>FOOD {world?.resources?.food??0}</span><span>WOOD {world?.resources?.wood??0}</span><span>STONE {world?.resources?.stone??0}</span><span>TOOLS {world?.resources?.tools??0}</span><span>MEDICINE {world?.resources?.medicine??0}</span></div></section>
  <section className="layout"><div className="world"><div className="section-head"><div><small>THE SETTLEMENT</small><h2>Life is happening here.</h2></div><span>click a resident</span></div>{world&&<Settlement chars={chars} world={world} colors={colors} onSelect={setSelected}/>}</div>
  <aside><div className="section-head"><div><small>WORLD HISTORY</small><h2>Recent events</h2></div></div><div className="feed">{events.length?events.map(e=>e.action==='world_event'?<article key={e.id} className="world-event"><div className="event-meta">TICK {e.tick} · {String(e.metadata?.kind??'world').toUpperCase()}</div><b>The world</b><p>{e.narrative}</p></article>:<article key={e.id}><div className="event-meta">TICK {e.tick} · {e.action.toUpperCase()}</div><b>{e.actor_name}</b><p>{e.narrative}</p></article>):<p className="empty">The world has not recorded its first event yet.</p>}</div></aside></section>
  <section className="chronicle"><div className="section-head"><div><small>THE DAY CHRONICLE</small><h2>How each day went.</h2></div></div>{activeChron?<><div className="chron-tabs">{chron.map(c=><button key={c.day} className={c.day===activeChron.day?'on':''} onClick={()=>setChronDay(c.day)}>DAY {c.day}</button>)}</div><div className="chron-body"><div><small>{activeChron.season.toUpperCase()} · TICKS {activeChron.first_tick}–{activeChron.last_tick}</small><p className="chron-summary">{activeChron.summary}</p>{activeChron.stats?.resources_delta&&<div className="chron-chips">{Object.entries(activeChron.stats.resources_delta as Record<string,number>).map(([k,v])=><span key={k} className={v>0?'up':v<0?'down':''}>{k.toUpperCase()} {v>0?'+':''}{v}</span>)}</div>}</div><div><small>HIGHLIGHTS</small>{activeChron.highlights.length?activeChron.highlights.map((h,i)=><p className="mini" key={i}><b>T{h.tick}</b> {h.text}</p>):<p className="empty">Nothing notable yet.</p>}</div></div></>:<p className="empty">The first chronicle entry will appear after the next tick.</p>}</section>
  <section className="residents"><div className="section-head"><div><small>THE RESIDENTS</small><h2>Nine lives, one shared history.</h2></div></div><div className="cards">{chars.map((c,i)=><button className="card" key={c.id} onClick={()=>setSelected(c)}><Avatar c={c} color={colors[i%colors.length]} size={44}/><div><h3>{c.name}</h3><small>{c.age} · {c.role}</small><p>{c.mood} · {c.current_activity}</p><p className="traits">{traitList(c.personality).slice(0,3).map(t=>t.trait).join(' · ')}</p></div><span className="chev">↗</span></button>)}</div></section>
  {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="drawer-av"><Avatar c={selected} color={colors[chars.findIndex(x=>x.id===selected.id)%colors.length]} size={72}/></div><small>{selected.role.toUpperCase()} · AGE {selected.age}</small><h2>{selected.name}</h2><p className="mood">{selected.mood} · {selected.current_activity}</p>{selected.last_reason&&<p className="reason">“{selected.last_reason}”</p>}<div className="bars"><div><span>FOOD</span><b>{selected.needs?.food??0}</b></div><div><span>ENERGY</span><b>{selected.needs?.energy??0}</b></div><div><span>SOCIAL</span><b>{selected.needs?.social??0}</b></div><div><span>HEALTH</span><b>{selected.needs?.health??0}</b></div></div><h4>PERSONALITY</h4><div className="traitbars">{traitList(selected.personality).map(t=><div key={t.trait}><span>{t.trait}</span><i><u style={{width:`${Math.round(t.weight*100)}%`}}/></i><em>{t.weight.toFixed(2)}</em></div>)}</div>{selectedRels.length>0&&<><h4>RELATIONSHIPS</h4>{selectedRels.map(r=><p className="rel" key={r.other}><b>{r.other}</b> <span>{r.label}</span> <em>{r.affinity>=0?'+':''}{r.affinity.toFixed(2)}</em></p>)}</>}<h4>GOALS</h4><ul>{(selected.goals||[]).map((g:string)=><li key={g}>{g}</li>)}</ul><h4>RECENT HISTORY</h4>{selectedEvents.map(e=><p className="mini" key={e.id}>{e.narrative}</p>)}</div></div>}
  <footer><span>THE NINE · SIMULATION EXPERIMENT 001</span><span>AI behavior is simulated. The system does not claim consciousness.</span></footer>
 </main>
}
